name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]       # run on all branches, including main, remove main post main lock
  pull_request:
    branches: [ "main" ]     # run on PRs targeting main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew test testCodeCoverageReport

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v4
